### PR TITLE
Manifest publish

### PR DESCRIPTION
**Pull request by bruceyclee**
@vijayrkn 
@sayedihashimi 
1. change publish module by using manifest provider
2. update associated test script

### CODE REVIEW

**Comment by sayedihashimi** [comment]
@bruceyclee did you get added to the Microsoft org in GitHub? The message above makes me think not. Contact Eilon to get added.

**Comment by bruceyclee** [comment]
@sayedihashimi 
@vijayrkn 
I just got my CLA signed. It's good to go on now.

**Comment by bruceyclee** [comment]
@sayedihashimi 
@vijayrkn 
Just push the script for EF migration functionality, including publish module and associated unit test files

**Comment by sayedihashimi** [comment]
Ok so can we close this pr then?

**Comment by bruceyclee** [comment]
@sayedihashimi 
@vijayrkn 
I just pushed the update of InternalNew-ManifestFile function (fix an error about multiple dbFullSql providers) and also add unit tests for this function.

**Comment by bruceyclee** [comment]
I think the line break issue made the files cannot be viewed on GitHub. I will find a way out to fix it and let you both can review the differences between existing and new versions before we close this PR. 
Thanks,

**Comment by bruceyclee** [comment]
@sayedihashimi 
@vijayrkn 
The problem has been fixed. Now you can review the "files changed" and they are working to show the differences between previous version and current version.
Thanks,

**Comment by bruceyclee** [comment]
close this old PR.

**Pull request closed without merging**
