### PR TITLE
Fixing the file encoding for manifest files

### PR DESCRIPTION
**Pull request by vijayrkn**
@sayedihashimi  @mlorbetske

### CODE REVIEW

**Comment by sayedihashimi** [comment]
For out-file here you may want to use -LiteralPath. I think other areas need this same update as well.

**Comment by vijayrkn** [comment]
-LiteralPath is not supported in older versions of Powershell. On win7 (with version 2) this is not supported.

**Comment by sayedihashimi** [comment]
Ok thanks

**Comment by mlorbetske** [comment]
LGTM then

**Pull request merged**
